# FUNZIONI PRINCIPALI DI NUMPY

In [2]:
# alias: importo una libreria e poi la uso con il nome che decido
import numpy as np

### CREAZIONE DELL'ARRAY

In [4]:
#creazione classica
lista = [1,2,3,4]
array = np.array(lista)
#diventa un array di tipo numpy
type(array)

numpy.ndarray

### OPERATORI SU ARRAY E LISTE

In [5]:
#l'array moltiplica ogni valore per quello definito (3)
3*array
#la lista ripete la lista di elementi per il valore definito (3)
3*lista

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]

### COPIA E MODIFICHE VELOCI NELL'ARRAY

In [20]:
#copia dell'array
a = array.copy()
#sencondo array con gli elementi invertiti
b = np.array(lista[::-1])
#somma ogni elemento in ordine tra i due array
a+b

### FUNZIONI STANDARD NUMPY

In [ ]:
#array di zeri (normalmente float)
zeri = np.zeros(10)
#per farli interi
zeri = np.zeros(10, dtype=np.int8)

#array di uno (sempre in float)
uni = np.ones(10)


### ARRAY PSEUDO-CASUALI

In [12]:
#array da 10 con valori compresi tra 1 e 2
np.random.uniform(1,2, 10)
# se voglio creare dei float
np.random.uniform(0., 10., 5)

#posso anche richiamare il paramtero tramite il nome della funzione
np.random.uniform(size = 10)

#per i valori interi (estremo low: incluso; esteremo High: escluso)
np.random.randint(1,6,10)


3.2073108120825964


#### ESEMPIO CON UN LANCIO DADI

In [32]:
#lanci di due dadi per 10 volte
alice = np.random.randint(1,7,10)
bob = np.random.randint(1,7,10)

#stampo i valori
print(f"Lanci di Alice: {alice}")
print(f"Lanci di Bob: {bob}")

#voglio vedere quante volte alice ha avuto un risultato maggiore a quello di bob
aliceVince = alice > bob

#il dtype della lista sarà intero 
alice.dtype

#il dtype dell'array sarà bool
aliceVince.dtype

Lanci di Alice: [2 5 5 5 6 5 1 5 3 5]
Lanci di Bob: [6 6 3 1 6 4 6 2 2 6]


dtype('bool')

#### INIDICIZZAZIONE BOOLEANA

In [31]:
#verifico per quali valori alice vince contro bob e viceversa(restituisce un array)
alice[aliceVince]
bob[aliceVince]

array([1, 4, 1, 1])

### FUNZIONI CON I NUMERI NUMPY

In [30]:
#ritorna dei valori equispaziati in un intervallo
#va da n1 a n2 facendo salti di n3 (ultimo SEMPRE escluso)
np.arange(3,20,3)
np.arange(20)

#intervalli di numeri reali
#suddivide in un intervallo[n1, n2] crea un'array di n3 valori dove i numeri sono divisi in parti uguali
np.linspace(0.0, 5.0, 11)

#inverte un array
arrayInvertito = array[::-1]

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

#### ESERCIZIO TESTA-CROCE

In [29]:
#sceglie un valore a caso da una lista, se voglio fare un array aggiungo il
# valore di numeri che devono essere estratti
print(np.random.choice(["Testa", "Croce"]))
print(np.random.choice(["Testa", "Croce"], 5))

#si può simulare una moneta truccata, ovvero che posso aggiungere una probabilità agli eventi
#la somma delle probabilità DEVE essere 1
print(np.random.choice(["Testa", "Croce"], 10, p=[.7,.3]))

Testa
['Croce' 'Croce' 'Testa' 'Croce' 'Croce']
['Croce' 'Testa' 'Testa' 'Testa' 'Testa' 'Croce' 'Testa' 'Croce' 'Croce'
 'Testa']


### CURVA GAUSSIANA o NORMALE

In [15]:
#crea un array con valore medio, varianza, dimensione
np.random.normal(1., 1., 10)

#curva dell'altezza delle persone (array unidimensionale)
altezze = np.random.normal(178, 10, 20)

#stampa una matrice con n1 righe e n2 colonne della tupla (bidimensionali)
# secondo indice gaussiano
altezze = np.random.normal(178, 10, (5,7))

### MASSIMI e MINIMI

In [17]:
np.max(altezze)
np.min(altezze)

159.15681940040312

### MATRICI

In [20]:
#generazione di array bidimensionali partendo da una lista
array_2d = np.array([[1,2,3], [4,5,6]])
# shape restituisce il numero di righe e colonne (array_2d.shape)

In [21]:
#generatore di matrici casuale
array_2d_casuale = np.random.uniform(0., 1., (8, 2))

In [23]:
#stampa il valore dell'array nella prima riga e prima colonna
array_2d_casuale[0,0]
#stampo la prima colonna
array_2d_casuale[:,0]
#tutto l'array
array_2d_casuale[:,:]

array([[0.49692945, 0.71673625],
       [0.30173185, 0.21109099],
       [0.58060326, 0.15963761],
       [0.84174841, 0.39520014],
       [0.83058476, 0.87585115],
       [0.26001379, 0.8991743 ],
       [0.42387856, 0.65177085],
       [0.75245719, 0.23619236]])

#### BLOCCO delle MATRICI

In [26]:
# simile allo slicing di python; stampo dalla riga 2 alla riga 5 esclusa
array_2d_casuale[2:5,:]

# il blocco si può anche usare per assegnare
# sostituisco 1. in tutti gli elementi di quel blocco
array_2d_casuale[2:5,:] = 1.

### INDICIZZAZIONE BOOLEANA

In [27]:
#array numpy indicizzati come booleani
array = np.arange(0, 5)

#trovo solo i numeri pari
divisibilePerDue = array%2==0
array[divisibilePerDue]

#posso anche fare delle assegnazioni
array[divisibilePerDue] = 999

array([0, 2, 4])

### FANCY INDEXING o ARRAY DI INDICI

In [4]:
# creo un array di 10 numeri float casuali
array = np.random.uniform(0., 1., 10)
# assegna a più elementi contemporaneamente il valore
array[np.array([1,2,9])] = 999
array

array([8.78567113e-03, 9.99000000e+02, 9.99000000e+02, 6.59914459e-02,
       7.52760172e-01, 4.39473021e-01, 9.24594833e-01, 6.12415645e-01,
       4.90412631e-01, 9.99000000e+02])

### OPERAZIONI MATEMATICHE: IL BROADCAST
##### il broadcast combina due o più array con operazioni matematiche (a patto che abbiano stessa dimensione)

In [9]:
array = np.array([1, 2, 3, 4, 5])

# moltiplicazione
array * 2

array([11, 12, 13, 14, 15])

In [12]:
# somma
array + 10

array([11, 12, 13, 14, 15])

In [13]:
# elevamento a potenza
np.exp(array)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [14]:
# radice quadrata
np.sqrt(array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

### IL BROADCAST

In [15]:
array2 = np.array([-1, -2, -3, -4, -5])
# somma elemento per elemento
# si possono sommare solo array della stessa dimensione
array + array2

array([0, 0, 0, 0, 0])

In [3]:
# il broadcast funziona anche sulle matrici
matrice = np.ones((5,5))
# posso sommare tutti gli eementi (mettendo 5,5)
# tutte le colonne (5, 1)
matrice2 = np.random.uniform(0,1,(5,1))
matrice + matrice2

array([[1.36055021, 1.36055021, 1.36055021, 1.36055021, 1.36055021],
       [1.07299018, 1.07299018, 1.07299018, 1.07299018, 1.07299018],
       [1.3208938 , 1.3208938 , 1.3208938 , 1.3208938 , 1.3208938 ],
       [1.72702613, 1.72702613, 1.72702613, 1.72702613, 1.72702613],
       [1.66178499, 1.66178499, 1.66178499, 1.66178499, 1.66178499]])

In [5]:
# creo una matrice di 5
matrice_5 = 4+np.ones((5, 5))
matrice_5

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])