# ESERCIZIO 6 PAGINA 107

In [41]:
import numpy as np

In [42]:
# creo un array di n valori
n = 15
array = np.random.randint(0, 10, n)
array

array([9, 4, 0, 9, 6, 0, 1, 2, 7, 6, 6, 2, 4, 9, 7])

In [43]:
# costruisco un array di n valori per trovare la posizione dei valori nell'array
array_posizioni = np.arange(0, n)
# cerco la posizione di un valore all'interno dell'array
array_posizioni[array == 1]

array([6])

In [44]:
# verifico quando nell'array si trova un uno
array == 1

array([False, False, False, False, False, False,  True, False, False,
       False, False, False, False, False, False])

In [45]:
# verifico se il valore successivo è il 2
# utilizzo il roll spostando verso sinistra tutti i valori dell'array
# (2 sarà nella posizione iniziale di 1)
np.roll(array, -1) == 2

array([False, False, False, False, False, False,  True, False, False,
       False,  True, False, False, False, False])

In [46]:
# creo la sequenza 12 facendo un and tra i due array
# (che restituiscono true solo se entrambi sono true)
sequenza12 = np.logical_and(array == 1, np.roll(array, -1) == 2)
sequenza12

array([False, False, False, False, False, False,  True, False, False,
       False, False, False, False, False, False])

In [47]:
# stampo il valore nell'array dove la sequenza 12 è true
array_posizioni[sequenza12]

array([6])

In [48]:
# ripeto lo stesop rocedimento per il valore 3
sequenza123 = np.logical_and(sequenza12, np.roll(array, -2) == 3)
array_posizioni[sequenza123]

array([], dtype=int32)